export const senderNames = [
    "Pertamina",
    "Telkom Indonesia",
    "Bank Mandiri",
    "Bank Rakyat Indonesia",
    "Bank Central Asia",
    "Astra International",
    "Unilever Indonesia",
    "Indofood Sukses Makmur",
    "Gudang Garam",
    "Sinar Mas Multiartha",
    "Medco Energi Internasional",
    "United Tractors",
    "Bank Negara Indonesia",
    "HM Sampoerna",
    "Indocement Tunggal Prakarsa",
    "Semen Indonesia",
    "Perusahaan Gas Negara",
    "Wijaya Karya",
    "Waskita Karya",
    "Bank Tabungan Negara",
    "Metrodata Electronics",
    "FKS Multi Agro",
    "Bentoel Internasional",
    "Jasa Marga",
    "Gajah Tunggal",
    "Catur Sentosa Adiprana",
    "Tigaraksa Satria",
    "Sido Muncul",
    "Insera Sena",
    "Bogasari Flour Mills",
    "Indah Jaya",
    "Chandra Asri Petrochemical",
    "Bayan Resources",
    "Indo Tambangraya Megah",
    "Adaro Energy",
    "Astra Agro Lestari",
    "Bank Jago",
    "Elang Mahkota Teknologi",
    "Kalbe Farma",
    "Charoen Pokphand Indonesia",
    "Bumi Resources",
    "Pakuwon Jati",
    "Surya Citra Media",
    "Summarecon Agung",
    "Sri Rejeki Isman",
    "Aneka Tambang",
    "AKR Corporindo",
    "Adhi Karya",
    "Barito Pacific",
    "Indoritel Makmur Internasional",
    "Indofood CBP Sukses Makmur",
    "Bank Danamon Indonesia",
    "Trakindo Utama",
    "GoTo Group",
    "Djarum Group",
    "ALAMI Sharia",
    "GO-JEK Indonesia",
    "Ralali Marketplace",
    "Xendit Payments",
    "IDI Smart Clinic",
    "Klinik Pintar",
    "CoLearn Education",
    "Dekoruma Living",
    "Lifepack Pharmacy",
    "Hangry Foods",
    "Matahari Putra Prima",
    "Ramayana Lestari Sentosa",
    "Mitra Adiperkasa",
    "Alfamart Retail",
    "Trans Retail Indonesia",
    "AEON Indonesia",
    "Lotte Mart Indonesia",
    "Samsung Indonesia",
    "Nike Indonesia",
    "Google Indonesia",
    "Marriott International",
    "Maybank Indonesia",
    "Coca-Cola Indonesia",
    "Procter & Gamble Indonesia",
    "Honda Indonesia",
    "LG Electronics Indonesia",
    "Epson Indonesia",
    "Danone Indonesia",
    "Adidas Indonesia",
    "Asus Indonesia",
    "Nestle Indonesia",
    "Toyota Indonesia",
    "Microsoft Indonesia",
    "Philip Morris Indonesia",
    "Jardine Matheson Indonesia",
    "L’Oreal Indonesia",
    "Johnson & Johnson Indonesia",
    "Accenture Indonesia",
    "Chevron Pacific Indonesia",
    "Shopee Indonesia",
    "Tokopedia Indonesia",
    "Wardah Cosmetics",
    "Grab Indonesia",
    "KFC Indonesia",
    "McDonald’s Indonesia",
    "Bank BCA Syariah",
    "BCA Finance",
    "BCA Sekuritas",
    "Asuransi Umum BCA",
    "Unilever Foods",
    "Bank OCBC NISP",
    "Sea Group Indonesia",
    "Sinar Mas Agribusiness",
    "Garuda Indonesia",
    "Lion Air",
    "Bumi Serpong Damai",
    "Lippo Karawaci",
    "Agung Podomoro Land",
    "Ciputra Development",
    "Bank Permata",
    "Multipolar Technology",
    "Multistrada Arah Sarana",
    "Bumi Resources Minerals",
    "Indosat Ooredoo",
    "XL Axiata",
    "Telkomsel Indonesia",
    "Smartfren Telecom",
    "Erajaya Swasembada",
    "MNC Vision Networks",
    "Global Mediacom",
    "Bakrie & Brothers",
    "Bakrie Telecom",
    "Bank Panin",
    "Bank Maybank Syariah",
    "Bank CIMB Niaga",
    "Bank BTPN",
    "Bank DBS Indonesia",
    "Bank HSBC Indonesia",
    "Bank Standard Chartered",
    "Bank UOB Indonesia",
    "Bank Commonwealth",
    "Bank Bukopin",
    "Bank Maspion",
    "Bank Sinarmas",
    "Bank Mayapada",
    "Bank QNB Indonesia",
    "Bank Woori Saudara",
    "Bank Shinhan Indonesia",
    "Bank J Trust Indonesia",
    "Bank Ganesha",
    "Bank BRI Agroniaga",
    "Bank Sahabat Sampoerna",
    "Bank BNI Syariah",
    "Bank Mandiri Taspen",
    "Bank Muamalat",
    "Bank Panin Syariah",
    "Bank Mega Syariah",
    "Bank BJB",
    "Bank DKI",
    "Bank Jatim",
    "Bank Jateng",
    "Bank BPD Bali",
    "Bank BPD DIY",
    "Bank Sumsel Babel",
    "Bank Jambi",
    "Bank Kalbar",
    "Bank Kaltim",
    "Bank Sulselbar",
    "Bank NTB",
    "Bank NTT",
    "Bank Maluku",
    "Bank Papua",
    "Bank Bengkulu",
    "Bank Sulteng",
    "Bank Sultra",
    "Bank Aceh",
    "Bank Nagari",
    "Bank Riau Kepri",
    "Bank Sumut",
    "Bank Kalteng",
    "Bank Lampung",
    "Bank Banten",
    "Bank BPD Kalsel",
    "Bank BPD Sulut",
    "Bank BPD Gorontalo",
    "Bank BPD Malut",
    "Bank BPD NTB Syariah",
    "Bank BPD Aceh Syariah",
    "Bank BPD Riau Syariah",
    "Bank BPD Sumut Syariah",
    "Bank BPD Kalsel Syariah",
    "Bank BPD Jatim Syariah",
    "Bank BPD Jateng Syariah",
    "Bank BPD DIY Syariah",
    "Bank BPD Sumsel Babel Syariah",
    "Bank BPD Kalbar Syariah",
    "Bank BPD Kaltim Syariah",
    "Bank BPD Sulselbar Syariah",
    "Bank BPD Bali Syariah",
    "Bank BPD Jambi Syariah",
    "Bank BPD Lampung Syariah",
    "Bank BPD Bengkulu Syariah",
    "Bank BPD Sulteng Syariah",
    "Bank BPD Sultra Syariah",
    "Bank BPD Maluku Syariah",
    "Bank BPD Papua Syariah",
    "Bank BPD Nagari Syariah",
    "Bank BPD Banten Syariah",
    "Bank BPD Kalteng Syariah",
    "Bank BPD Gorontalo Syariah",
    "Bank BPD Malut Syariah",
    "Bank BPD Sumut Agroniaga",
    "Bank BPD Jatim Agroniaga",
    "Bank BPD Jateng Agroniaga",
    "Bank BPD DIY Agroniaga",
    "Bank BPD Sumsel Babel Agroniaga",
    "Bank BPD Kalbar Agroniaga",
    "Bank BPD Kaltim Agroniaga",
    "Bank BPD Sulselbar Agroniaga",
    "Bank BPD Bali Agroniaga",
    "Bank BPD Jambi Agroniaga",
    "Bank BPD Lampung Agroniaga",
    "Bank BPD Bengkulu Agroniaga",
    "Bank BPD Sulteng Agroniaga",
    "Bank BPD Sultra Agroniaga",
    "Bank BPD Maluku Agroniaga",
    "Bank BPD Papua Agroniaga",
    "Bank BPD Nagari Agroniaga",
    "Bank BPD Banten Agroniaga",
    "Bank BPD Kalteng Agroniaga",
    "Bank BPD Gorontalo Agroniaga",
    "Bank BPD Malut Agroniaga",
    "Sari Roti",
    "Blue Bird Group",
    "Express Transindo",
    "Sinar Mas Land",
    "Lippo Group",
    "Salim Group",
    "Djarum Indonesia",
    "Sampoerna Strategic",
    "Wings Group",
    "Mayora Indah",
    "Siantar Top",
    "Tjiwi Kimia",
    "Indah Kiat Pulp",
    "Asia Pulp & Paper",
    "Gunung Sewu Group",
    "Triputra Group",
    "Para Group",
    "CT Corp",
    "Trans Corp",
    "MNC Group",
    "Kompas Gramedia",
    "Femina Group",
    "Tempo Media",
    "Berita Satu Media",
    "Viva Media",
    "Emtek Group",
    "SCTV Network",
    "RCTI Network",
    "Indosiar Network",
    "Metro TV",
    "TVRI Indonesia",
    "Net TV Indonesia",
    "Okezone Media",
    "CNN Indonesia",
    "CNBC Indonesia",
    "Kompas TV",
    "Trans TV",
    "Trans7 TV",
    "ANTV Indonesia",
    "RTV Indonesia",
    "iNews TV",
    "Jakarta Globe",
    "The Jakarta Post",
    "Bisnis Indonesia",
    "Investor Daily",
    "Kontan Media",
    "Sindo Media",
    "Media Indonesia",
    "Republika Media",
    "Suara Pembaruan",
    "Harian Kompas",
    "Jawa Pos",
    "Pikiran Rakyat",
    "Tribun News",
    "Detikcom Media",
    "Liputan6 Media",
    "Vivanews Media",
    "Merdeka Media",
    "Kumparan Media",
    "Traveloka Indonesia",
    "Bukalapak Ecommerce",
    "Lazada Indonesia",
    "Blibli Commerce",
    "JD.ID Indonesia",
    "Zalora Indonesia",
    "Sociolla Beauty",
    "Orami Indonesia",
    "Berrybenka Fashion",
    "Pomelo Fashion",
    "Matahari Mall",
    "MAP Active",
    "ACE Hardware Indonesia",
    "Informa Furnishings",
    "Hypermart Indonesia",
    "Super Indo",
    "Giant Indonesia",
    "Carrefour Indonesia",
    "Hero Supermarket",
    "Lotte Shopping Indonesia",
    "Indomaret Retail",
    "Alfamidi Retail",
    "Circle K Indonesia",
    "Lawson Indonesia",
    "7-Eleven Indonesia",
    "Sogo Department Store",
    "Seibu Indonesia",
    "Metro Department Store",
    "Centro Department Store",
    "Parkson Indonesia",
    "Debenhams Indonesia",
    "Marks & Spencer Indonesia",
    "H&M Indonesia",
    "Zara Indonesia",
    "Uniqlo Indonesia",
    "Pull & Bear Indonesia",
    "Bershka Indonesia",
    "Stradivarius Indonesia",
    "Mango Indonesia",
    "Forever 21 Indonesia",
    "Cotton On Indonesia",
    "Topshop Indonesia",
    "Topman Indonesia",
    "GAP Indonesia",
    "Banana Republic Indonesia",
    "Old Navy Indonesia",
    "Levi’s Indonesia",
    "Wrangler Indonesia",
    "Lee Indonesia",
    "The Executive",
    "Matahari Department Store",
    "Ramayana Department Store",
    "Yogya Department Store",
    "Sarinah Department Store",
    "Pasaraya Grande",
    "Centro Lifestyle",
    "Sports Station",
    "Planet Sports",
    "Sports Warehouse",
    "Adidas Originals Indonesia",
    "Nike Store Indonesia",
    "Puma Indonesia",
    "Reebok Indonesia",
    "Under Armour Indonesia",
    "New Balance Indonesia",
    "Skechers Indonesia",
    "Vans Indonesia",
    "Converse Indonesia",
    "Fila Indonesia",
    "Asics Indonesia",
    "Columbia Indonesia",
    "The North Face Indonesia",
    "Patagonia Indonesia",
    "Salomon Indonesia",
    "Merrell Indonesia",
    "Timberland Indonesia",
    "Dr. Martens Indonesia",
    "Clarks Indonesia",
    "Ecco Indonesia",
    "Crocs Indonesia",
    "Birkenstock Indonesia",
    "Teva Indonesia",
    "Chaco Indonesia",
    "Keen Indonesia",
    "Starbucks Indonesia",
    "Dunkin Donuts Indonesia",
    "Pizza Hut Indonesia",
    "Domino’s Pizza Indonesia",
    "Burger King Indonesia",
    "Wendy’s Indonesia",
    "Taco Bell Indonesia",
    "Subway Indonesia",
    "A&W Indonesia",
    "HokBen Indonesia",
    "Sari Rasa Group",
    "Sate Khas Senayan",
    "Bebek Kaleyo",
    "Es Teler 77",
    "Bakmi GM",
    "Solaria Indonesia",
    "Pepper Lunch Indonesia",
    "Yoshinoya Indonesia",
    "Marugame Udon Indonesia",
    "Sushi Tei Indonesia",
    "Hoka-Hoka Bento",
    "Pondok Indah Group",
    "D’Cost Seafood",
    "Warung Makan MJS",
    "Richeese Factory",
    "Kopi Kenangan",
    "Janji Jiwa Coffee",
    "Fore Coffee",
    "Tomoro Coffee",
    "Point Coffee",
    "Starbucks Reserve Indonesia",
    "J.CO Donuts Indonesia",
    "Krispy Kreme Indonesia",
    "BreadTalk Indonesia",
    "Holland Bakery",
    "Tous Les Jours Indonesia",
    "Harvest Cakes",
    "The Harvest Patisserie",
    "Dapur Cokelat",
    "Union Bakery Indonesia",
    "Beard Papa’s Indonesia",
    "Cinnabon Indonesia",
    "Auntie Anne’s Indonesia",
    "Cold Stone Creamery",
    "Baskin Robbins Indonesia",
    "Haagen-Dazs Indonesia",
    "Gelato Secrets",
    "Grom Gelato Indonesia",
    "Venchi Indonesia",
    "Godiva Indonesia",
    "Magnum Indonesia",
    "Walls Indonesia",
    "Campina Ice Cream",
    "Aice Indonesia",
    "Glico Indonesia",
    "Meiji Indonesia",
    "Morinaga Indonesia",
    "Lotte Indonesia",
    "Nestle Milo Indonesia",
    "Frisian Flag Indonesia",
    "Ultra Milk Indonesia",
    "Indomilk Indonesia",
    "Greenfields Indonesia",
    "Yakult Indonesia",
    "Vitacharm Indonesia",
    "Anlene Indonesia",
    "Bear Brand Indonesia",
    "Dancow Indonesia",
    "Milo Indonesia",
    "Susu Bendera",
    "Cimory Indonesia",
    "Yogya Supermarket",
    "Gelael Supermarket",
    "Foodhall Indonesia",
    "Ranch Market Indonesia",
    "Farmers Market Indonesia",
    "Grand Lucky Indonesia",
    "The FoodHall",
    "Lotte Mart Wholesale",
    "Makro Indonesia",
    "Costco Indonesia",
    "Walmart Indonesia",
    "Target Indonesia",
    "Kroger Indonesia",
    "IKEA Indonesia",
    "Ace Hardware International",
    "Home Depot Indonesia",
    "Lowe’s Indonesia",
    "Best Buy Indonesia",
    "Decathlon Indonesia",
    "Intersport Indonesia",
    "JD Sports Indonesia",
    "Sport 2000 Indonesia",
    "Courts Indonesia",
    "Electronic City Indonesia",
    "Best Denki Indonesia",
    "Erafone Indonesia",
    "iBox Indonesia",
    "Samsung Store Indonesia",
    "Xiaomi Indonesia",
    "Huawei Indonesia",
    "Oppo Indonesia",
    "Vivo Indonesia",
    "Realme Indonesia",
    "OnePlus Indonesia",
    "Sony Indonesia",
    "Panasonic Indonesia",
    "Philips Indonesia",
    "Sharp Indonesia",
    "Toshiba Indonesia",
    "Mitsubishi Electric Indonesia",
    "Daikin Indonesia",
    "Carrier Indonesia",
    "LG Home Appliances",
    "Electrolux Indonesia",
    "Whirlpool Indonesia",
    "Bosch Indonesia",
    "Siemens Indonesia",
    "Midea Indonesia",
    "Hitachi Indonesia",
    "Sanyo Indonesia",
    "Aqua Indonesia",
    "Polytron Indonesia",
    "Modena Indonesia",
    "Ariston Indonesia",
    "Rinnai Indonesia",
    "Shimizu Indonesia",
    "Sanken Indonesia",
    "Cosmos Indonesia",
    "Miyako Indonesia",
    "Oxone Indonesia",
    "Kirin Indonesia",
    "Philips Lighting Indonesia",
    "Osram Indonesia",
    "GE Lighting Indonesia",
    "Panasonic Lighting Indonesia",
    "Havells Indonesia",
    "Surya Roshni Indonesia",
    "Bajaj Indonesia",
    "Wipro Consumer Indonesia",
    "Godrej Indonesia",
    "Eureka Forbes Indonesia",
    "Blue Star Indonesia",
    "Voltas Indonesia",
    "Dyson Indonesia",
    "Karcher Indonesia",
    "Nilfisk Indonesia",
    "Tennant Indonesia",
    "Hako Indonesia",
    "Alfred Karcher Indonesia",
    "Bissell Indonesia",
    "Hoover Indonesia",
    "Eureka Indonesia",
    "Shark Indonesia",
    "Roborock Indonesia",
    "iRobot Indonesia",
    "Ecovacs Indonesia",
    "Xiaomi Robotics Indonesia",
    "Samsung Robotics Indonesia",
    "LG Robotics Indonesia",
    "Panasonic Robotics Indonesia",
    "Sony Robotics Indonesia",
    "Toyota Robotics Indonesia",
    "Honda Robotics Indonesia",
    "Hyundai Indonesia",
    "Kia Indonesia",
    "Mazda Indonesia",
    "Mitsubishi Motors Indonesia",
    "Suzuki Indonesia",
    "Daihatsu Indonesia",
    "Isuzu Indonesia",
    "Hino Indonesia",
    "Mercedes-Benz Indonesia",
    "BMW Indonesia",
    "Audi Indonesia",
    "Volkswagen Indonesia",
    "Porsche Indonesia",
    "Lexus Indonesia",
    "Land Rover Indonesia",
    "Jaguar Indonesia",
    "Volvo Indonesia",
    "Mini Cooper Indonesia",
    "Tesla Indonesia",
    "BYD Indonesia",
    "Nissan Indonesia",
    "Subaru Indonesia",
    "Jeep Indonesia",
    "Chevrolet Indonesia",
    "Ford Indonesia",
    "Chrysler Indonesia",
    "Dodge Indonesia",
    "Ram Trucks Indonesia",
    "Geely Indonesia",
    "Great Wall Motors Indonesia",
    "Chery Indonesia",
    "MG Motor Indonesia",
    "Wuling Indonesia",
    "DFSK Indonesia",
    "Tata Motors Indonesia",
    "Mahindra Indonesia",
    "Proton Indonesia",
    "Perodua Indonesia",
    "VinFast Indonesia",
    "XPeng Indonesia",
    "NIO Indonesia",
    "Li Auto Indonesia",
    "Hozon Auto Indonesia",
    "Serum Institute Indonesia",
    "Bio Farma Indonesia",
    "Kalbio Global Medika",
    "Kimia Farma",
    "Phapros Indonesia",
    "Tempo Scan Pacific",
    "Darya-Varia Laboratoria",
    "Merck Indonesia",
    "Pfizer Indonesia",
    "Novartis Indonesia",
    "Sanofi Indonesia",
    "Bayer Indonesia",
    "GlaxoSmithKline Indonesia",
    "AstraZeneca Indonesia",
    "Roche Indonesia",
    "Abbott Indonesia",
    "MSD Indonesia",
    "Boehringer Ingelheim Indonesia",
    "Takeda Indonesia",
    "Novo Nordisk Indonesia",
    "Eli Lilly Indonesia",
    "Amgen Indonesia",
    "Gilead Sciences Indonesia",
    "Biogen Indonesia",
    "Moderna Indonesia",
    "Regeneron Indonesia",
    "Vertex Indonesia",
    "Sandoz Indonesia",
    "Teva Indonesia",
    "Mylan Indonesia",
    "Sun Pharma Indonesia",
    "Cipla Indonesia",
    "Dr. Reddy’s Indonesia",
    "Lupin Indonesia",
    "Aurobindo Indonesia",
    "Zydus Cadila Indonesia",
    "Torrent Pharma Indonesia",
    "Glenmark Indonesia",
    "Alkem Laboratories Indonesia",
    "Intas Pharmaceuticals Indonesia",
    "Hetero Drugs Indonesia",
    "Macleods Indonesia",
    "Wockhardt Indonesia",
    "Ipca Laboratories Indonesia",
    "Emcure Indonesia",
    "Ajanta Pharma Indonesia",
    "Natco Pharma Indonesia",
    "Strides Pharma Indonesia",
    "Laurus Labs Indonesia",
    "Divis Laboratories Indonesia",
    "Cadila Healthcare Indonesia",
    "Jubilant Life Sciences Indonesia",
    "Hikma Pharmaceuticals Indonesia",
    "Aspen Pharmacare Indonesia",
    "Orion Pharma Indonesia",
    "Krka Indonesia",
    "Gedeon Richter Indonesia",
    "Egis Pharmaceuticals Indonesia",
    "Servier Indonesia",
    "Menarini Indonesia",
    "Chiesi Indonesia",
    "Ferrer Indonesia",
    "Almirall Indonesia",
    "Grifols Indonesia",
    "CSL Behring Indonesia",
    "Baxter Indonesia",
    "Fresenius Kabi Indonesia",
    "Hospira Indonesia",
    "B. Braun Indonesia",
    "Terumo Indonesia",
    "Nipro Indonesia",
    "Smith & Nephew Indonesia",
    "Dentsply Sirona Indonesia",
    "Hologic Indonesia",
    "Varian Medical Indonesia",
    "Intuitive Surgical Indonesia",
    "Align Technology Indonesia",
    "Zimmer Biomet Indonesia",
    "Stryker Indonesia",
    "Medtronic Indonesia",
    "Boston Scientific Indonesia",
    "Edwards Lifesciences Indonesia",
    "Hologic Indonesia",
    "Varian Medical Indonesia",
    "Intuitive Surgical Indonesia",
    "Align Technology Indonesia",
    "Zimmer Biomet Indonesia",
    "Stryker Indonesia",
    "Medtronic Indonesia",
    "Boston Scientific Indonesia",
    "Edwards Lifesciences Indonesia",
    "Apple Inc.",
    "Amazon",
    "Google",
    "Microsoft",
    "Tesla",
    "Toyota Motor Corporation",
    "Samsung Electronics",
    "Unilever",
    "Nestlé",
    "Coca-Cola",
    "PepsiCo",
    "Procter & Gamble",
    "Johnson & Johnson",
    "Pfizer",
    "Novartis",
    "Roche",
    "Merck & Co.",
    "Bayer",
    "GlaxoSmithKline",
    "Sanofi",
    "Walmart",
    "Alibaba Group",
    "Tencent Holdings",
    "Facebook (Meta)",
    "Intel",
    "NVIDIA",
    "Adobe",
    "Oracle",
    "Cisco Systems",
    "IBM",
    "General Electric",
    "Siemens",
    "Volkswagen Group",
    "BMW Group",
    "Mercedes-Benz Group",
    "Ford Motor Company",
    "General Motors",
    "Honda Motor Co.",
    "Hyundai Motor Company",
    "Nissan Motor Corporation",
    "Boeing",
    "Airbus",
    "Lockheed Martin",
    "Raytheon Technologies",
    "Nike",
    "Adidas",
    "L'Oréal",
    "Estée Lauder",
    "Colgate-Palmolive",
    "Kimberly-Clark",
    "McDonald's",
    "Starbucks",
    "Yum! Brands",
    "Marriott International",
    "Hilton Worldwide",
    "Visa",
    "Mastercard",
    "American Express",
    "JPMorgan Chase",
    "Goldman Sachs",
    "Morgan Stanley",
    "HSBC Holdings",
    "Bank of America",
    "Citigroup",
    "Wells Fargo",
    "Chevron",
    "ExxonMobil",
    "Shell",
    "BP",
    "TotalEnergies",
    "Saudi Aramco",
    "Intel",
    "AMD",
    "Qualcomm",
    "TSMC",
    "Sony",
    "Panasonic",
    "LG Electronics",
    "Dell Technologies",
    "HP Inc.",
    "Lenovo",
    "ASUS",
    "Acer",
    "Philips",
    "Bosch",
    "Hitachi",
    "Toshiba",
    "Mitsubishi Electric",
    "Nestlé",
    "Mondelez International",
    "Danone",
    "Kraft Heinz",
    "General Mills",
    "Kellogg's",
    "Mars, Incorporated",
    "Ferrero",
    "IKEA",
    "Home Depot",
    "Lowe's",
    "Costco Wholesale",
    "Target Corporation",
    "Amazon Web Services",
    "Accenture",
    "Deloitte",
    "PwC",
    "EY",
    "KPMG",
    "AT&T",
    "Verizon",
    "China Mobile",
    "Deutsche Telekom",
    "Vodafone",
    "SoftBank",
    "Berkshire Hathaway",
    "BlackRock",
    "Nestlé Waters",
    "Diageo",
    "Anheuser-Busch InBev",
    "Heineken",
    "Carlsberg",
    "Pernod Ricard",
    "LVMH",
    "Kering",
    "Richemont",
    "Hermès",
    "Prada",
    "Gucci",
    "Rolex",
    "Omega",
    "Intel Corporation",
    "Broadcom",
    "Texas Instruments",
    "Medtronic",
    "Stryker",
    "Boston Scientific",
    "Becton Dickinson",
    "AstraZeneca",
    "Eli Lilly",
    "Novo Nordisk",
    "Amgen",
    "Gilead Sciences",
    "Moderna",
    "Regeneron Pharmaceuticals",
    "Vertex Pharmaceuticals",
    "Baidu",
    "JD.com",
    "Pinduoduo",
    "ByteDance",
    "Netflix",
    "Disney",
    "Comcast",
    "Warner Bros. Discovery",
    "Paramount Global",
    "Spotify",
    "Eldorado Gold",
    "Barrick Gold",
    "Newmont Corporation",
    "Anglo American",
    "BHP Group",
    "Rio Tinto",
    "Vale",
    "Glencore",
    "Caterpillar Inc.",
    "Deere & Company",
    "Komatsu",
    "Volvo Group",
    "CNH Industrial",
    "Kubota Corporation",
    "PepsiCo Foods",
    "UPS",
    "FedEx",
    "DHL",
    "Maersk",
    "Cosco Shipping",
    "Emirates Airline",
    "Lufthansa",
    "Delta Air Lines",
    "United Airlines",
    "American Airlines",
    "Singapore Airlines",
    "Qatar Airways",
    "Cathay Pacific",
    "Allianz",
    "AXA",
    "Zurich Insurance",
    "Prudential Financial",
    "MetLife",
    "AIG",
    "Ping An Insurance",
    "China Life Insurance",
    "Toyota Tsusho",
    "Mitsui & Co.",
    "Sumitomo Corporation",
    "Marubeni",
    "Itochu Corporation",
    "Reliance Industries",
    "Tata Group",
    "Adani Group",
    "Mahindra Group",
    "Hindustan Unilever",
    "Infosys",
    "TCS (Tata Consultancy Services)",
    "Wipro",
    "HCL Technologies",
    "Tech Mahindra",
    "SAP",
    "Salesforce",
    "ServiceNow",
    "Workday",
    "Intuit",
    "PayPal",
    "Square (Block, Inc.)",
    "Shopify",
    "Atlassian",
    "Zoom Video Communications",
    "Snowflake",
    "Palantir Technologies",
    "Crowdstrike",
    "Zscaler",
    "Fortinet",
    "Check Point Software",
    "Palo Alto Networks",
    "ABB",
    "Schneider Electric",
    "Emerson Electric",
    "Rockwell Automation",
    "Honeywell International",
    "3M",
    "DuPont",
    "Dow Inc.",
    "BASF",
    "Evonik Industries",
    "Syngenta",
    "Monsanto (Bayer)",
    "Corteva Agriscience",
    "FMC Corporation",
    "Ecolab",
    "Clorox",
    "Reckitt Benckiser",
    "Shiseido",
    "Beiersdorf",
    "Amway",
    "Herbalife",
    "Avon Products",
    "Mary Kay",
    "Tupperware Brands",
    "Natura &Co",
    "Foxconn",
    "Pegatron",
    "Quanta Computer",
    "Compal Electronics",
    "Wistron",
    "Luxshare Precision",
    "Goertek",
    "AAC Technologies",
    "Delta Electronics",
    "Eldorado Gold",
    "Kinross Gold",
    "Franco-Nevada",
    "Wheaton Precious Metals",
    "Royal Dutch Shell",
    "Eni",
    "Equinor",
    "Petrobras",
    "Sinopec",
    "China National Petroleum",
    "Rosneft",
    "Lukoil",
    "Gazprom",
    "ConocoPhillips",
    "Occidental Petroleum",
    "EOG Resources",
    "Pioneer Natural Resources",
    "Devon Energy",
    "Marathon Petroleum",
    "Valero Energy",
    "Phillips 66",
    "Neste",
    "Repsol",
    "Suncor Energy",
    "Canadian Natural Resources",
    "Imperial Oil",
    "Cenovus Energy",
    "Hess Corporation",
    "Apache Corporation",
    "Murphy Oil",
    "Baker Hughes",
    "Schlumberger",
    "Halliburton",
    "TechnipFMC",
    "National Oilwell Varco",
    "Weatherford International",
    "Subsea 7",
    "Saipem",
    "Transocean",
    "Enbridge",
    "Kinder Morgan",
    "Williams Companies",
    "TC Energy",
    "Enterprise Products Partners",
    "Magellan Midstream Partners",
    "Plains All American Pipeline",
    "Cheniere Energy",
    "Sempra Energy",
    "Dominion Energy",
    "Duke Energy",
    "Southern Company",
    "NextEra Energy",
    "Exelon",
    "American Electric Power",
    "PSEG",
    "Consolidated Edison",
    "Xcel Energy",
    "Edison International",
    "FirstEnergy",
    "Eversource Energy",
    "DTE Energy",
    "Entergy",
    "Fortis",
    "Hydro One",
    "Emera",
    "Algonquin Power & Utilities",
    "NRG Energy",
    "Vistra Energy",
    "AES Corporation",
    "CenterPoint Energy",
    "CMS Energy",
    "Atmos Energy",
    "NiSource",
    "WEC Energy Group",
    "Alliant Energy",
    "Evergy",
    "Pinnacle West Capital",
    "OGE Energy",
    "Portland General Electric",
    "Idacorp",
    "Hawaiian Electric Industries",
    "Avangrid",
    "Iberdrola",
    "Enel",
    "EDF",
    "Engie",
    "RWE",
    "E.ON",
    "Orsted",
    "Vestas Wind Systems",
    "Siemens Gamesa",
    "Goldwind",
    "Nordex",
    "Senvion",
    "GE Renewable Energy",
    "Nexans",
    "Prysmian Group",
    "Southwire Company",
    "General Cable",
    "NKT",
    "LS Cable & System",
    "Furukawa Electric",
    "Sumitomo Electric",
    "Hitachi Metals",
    "Mitsubishi Materials",
    "JFE Holdings",
    "Nippon Steel",
    "Posco",
    "ArcelorMittal",
    "Tata Steel",
    "Thyssenkrupp",
    "Salzgitter",
    "Voestalpine",
    "Nucor",
    "Steel Dynamics",
    "United States Steel",
    "Cleveland-Cliffs",
    "AK Steel",
    "Commercial Metals Company",
    "Gerdau",
    "Ternium",
    "Usiminas",
    "CSN (Companhia Siderúrgica Nacional)",
    "Severstal",
    "Evraz",
    "Metalloinvest",
    "NLMK Group",
    "MMK (Magnitogorsk Iron and Steel Works)",
    "Shougang Group",
    "Baosteel",
    "Ansteel",
    "Wuhan Iron and Steel",
    "Shagang Group",
    "Hesteel Group",
    "JFE Steel",
    "Kobe Steel",
    "Sumitomo Metal Industries",
    "Nisshin Steel",
    "Daido Steel",
    "Hitachi Metals",
    "Yamato Steel",
    "Tokyo Steel",
    "Aichi Steel",
    "Sanyo Special Steel",
    "Ovako",
    "Saarstahl",
    "Georgsmarienhütte",
    "Dillinger",
    "Salzgitter Flachstahl",
    "Thyssenkrupp Steel Europe",
    "Outokumpu",
    "Aperam",
    "Acerinox",
    "Sandvik",
    "Allegheny Technologies",
    "Carpenter Technology",
    "Haynes International",
    "Universal Stainless & Alloy Products",
    "TimkenSteel",
    "SSAB",
    "Ruukki",
    "BlueScope Steel",
    "Liberty Steel",
    "InfraBuild",
    "OneSteel",
    "Fortescue Metals Group",
    "Mineral Resources",
    "South32",
    "OZ Minerals",
    "Newcrest Mining",
    "Evolution Mining",
    "Northern Star Resources",
    "Saracen Mineral Holdings",
    "St Barbara",
    "Perseus Mining",
    "Resolute Mining",
    "Regis Resources",
    "Alacer Gold",
    "Centerra Gold",
    "Eldorado Gold",
    "Yamana Gold",
    "Agnico Eagle Mines",
    "Kirkland Lake Gold",
    "New Gold",
    "OceanaGold",
    "Endeavour Mining",
    "IAMGOLD",
    "B2Gold",
    "Pretium Resources",
    "Equinox Gold",
    "SSR Mining",
    "Alamos Gold",
    "Hecla Mining",
    "Coeur Mining",
    "First Majestic Silver",
    "Pan American Silver",
    "Wheaton Precious Metals",
    "Royal Gold",
    "Osisko Gold Royalties",
    "Sandstorm Gold",
    "Franco-Nevada",
    "Gold Fields",
    "Harmony Gold",
    "AngloGold Ashanti",
    "Sibanye-Stillwater",
    "Impala Platinum",
    "Anglo American Platinum",
    "Northam Platinum",
    "Lonmin",
    "Aquarius Platinum",
    "Royal Bafokeng Platinum",
    "Exxaro Resources",
    "Kumba Iron Ore",
    "African Rainbow Minerals",
    "Assore",
    "Assmang",
    "Petra Diamonds",
    "De Beers",
    "Alrosa",
    "Lucara Diamond",
    "Gem Diamonds",
    "Dominion Diamond",
    "Mountain Province Diamonds",
    "Star Diamond",
    "Rio Tinto Diamonds",
    "BHP Billiton Diamonds",
    "Anglo American Diamonds",
    "Tiffany & Co.",
    "Signet Jewelers",
    "Pandora",
    "Swarovski",
    "Chow Tai Fook",
    "Luk Fook",
    "Tanishq",
    "Malabar Gold & Diamonds",
    "Cartier",
    "Van Cleef & Arpels",
    "Bvlgari",
    "Chopard",
    "Piaget",
    "Graff",
    "Harry Winston",
    "Mikimoto",
    "Buccellati",
    "Damiani",
    "Pomellato",
    "Chaumet",
    "Boucheron",
    "Messika",
    "De Grisogono",
    "David Yurman",
    "John Hardy",
    "Monica Vinader",
    "Links of London",
    "Thomas Sabo",
    "Swarovski Crystal",
    "Montblanc",
    "Longines",
    "Tissot",
    "Rado",
    "Mido",
    "Baume & Mercier",
    "Tag Heuer",
    "Breitling",
    "IWC Schaffhausen",
    "Jaeger-LeCoultre",
    "Vacheron Constantin",
    "Audemars Piguet",
    "Patek Philippe",
    "A. Lange & Söhne",
    "Glashütte Original",
    "Nomos Glashütte",
    "Zenith",
    "Ulysse Nardin",
    "Blancpain",
    "Breguet",
    "Hublot",
    "Panerai",
    "Girard-Perregaux",
    "Bell & Ross",
    "Oris",
    "Tudor",
    "Frederique Constant",
    "Raymond Weil",
    "Chanel",
    "Dior",
    "Louis Vuitton",
    "Balenciaga",
    "Givenchy",
    "Saint Laurent",
    "Celine",
    "Fendi",
    "Bottega Veneta",
    "Valentino",
    "Versace",
    "Armani",
    "Dolce & Gabbana",
    "Burberry",
    "Moncler",
    "Canada Goose",
    "Arc'teryx",
    "Patagonia",
    "The North Face",
    "Columbia Sportswear",
    "Under Armour",
    "Asics",
    "Reiss",
    "Ted Baker",
    "Superdry",
    "AllSaints",
    "Ganni",
    "Zara",
    "H&M",
    "Uniqlo",
    "Primark",
    "Next",
    "Mango",
    "Massimo Dutti",
    "Bershka",
    "Pull & Bear",
    "Stradivarius",
    "Forever 21",
    "Topshop",
    "Topman",
    "River Island",
    "New Look",
    "Boohoo",
    "ASOS",
    "Missguided",
    "PrettyLittleThing",
    "Nasty Gal",
    "Zalando",
    "Farfetch",
    "Net-a-Porter",
    "Mytheresa",
    "SSENSE",
    "MatchesFashion",
    "Revolve",
    "Shopbop",
    "Nordstrom",
    "Macy's",
    "Saks Fifth Avenue",
    "Neiman Marcus",
    "Bloomingdale's",
    "Dillard's",
    "Kohl's",
    "JCPenney",
    "Sears",
    "Belk",
    "Lord & Taylor",
    "Hudson's Bay",
    "Galeries Lafayette",
    "Printemps",
    "Le Bon Marché",
    "Selfridges",
    "Harrods",
    "Liberty London",
    "Fortnum & Mason",
    "John Lewis Partnership",
    "Marks & Spencer",
    "Debenhams",
    "House of Fraser",
    "Fenwick",
    "Harvey Nichols",
    "Brown Thomas",
    "Arnotts",
    "El Corte Inglés",
    "La Rinascente",
    "Coin",
    "Rinascente",
    "KaDeWe",
    "Oberpollinger",
    "Alsterhaus",
    "Karstadt",
    "Breuninger",
    "Peek & Cloppenburg",
    "Zalando",
    "Otto Group",
    "About You",
    "C&A",
    "Kiabi",
    "Primark",
    "Pepco",
    "Takko Fashion",
    "Lidl",
    "Aldi",
    "Schwarz Group",
    "Rewe Group",
    "Edeka",
    "Tesco",
    "Sainsbury's",
    "Asda",
    "Morrisons",
    "Waitrose",
    "Co-op Food",
    "Iceland Foods",
    "Ocado",
    "Carrefour",
    "Auchan",
    "Leclerc",
    "Casino Group",
    "Intermarché",
    "Système U",
    "Monoprix",
    "Franprix",
    "Leader Price",
    "Dia",
    "Mercadona",
    "Eroski",
    "Alcampo",
    "Ahold Delhaize",
    "Albert Heijn",
    "Jumbo",
    "Plus",
    "Lidl Netherlands",
    "Aldi Nord",
    "Aldi Süd",
    "Netto",
    "Penny",
    "Norma",
    "Kaufland",
    "Real",
    "Globus",
    "Migros",
    "Coop Switzerland",
    "Denner",
    "Manor",
    "Spar",
    "Colruyt",
    "Delhaize",
    "Provera",
    "Cora",
    "Match",
    "Smatch",
    "Louis Delhaize",
    "Makro",
    "Metro AG",
    "Costco",
    "Sam's Club",
    "BJ's Wholesale Club",
    "Meijer",
    "Publix",
    "Kroger",
    "Albertsons",
    "Safeway",
    "Whole Foods Market",
    "Trader Joe's",
    "Sprouts Farmers Market",
    "H-E-B",
    "Wegmans",
    "Hy-Vee",
    "Giant Eagle",
    "Stop & Shop",
    "ShopRite",
    "Hannaford",
    "Food Lion",
    "Giant Food",
    "Martin's",
    "King Kullen",
    "Price Chopper",
    "Market Basket",
    "WinCo Foods",
    "Raley's",
    "Save Mart",
    "Stater Bros",
    "Bashas'",
    "Brookshire Grocery",
    "Ingles Markets",
    "Piggly Wiggly",
    "Schnucks",
    "Roundy's",
    "Harris Teeter",
    "Weis Markets",
    "Lowes Foods",
    "Food City",
    "Fareway",
    "Buehler's",
    "Dierbergs",
    "Jungle Jim's",
    "Roche Bros",
    "Big Y",
    "Acme Markets",
    "Shaws",
    "Star Market",
    "Jewel-Osco",
    "Vons",
    "Pavilions",
    "Randalls",
    "Tom Thumb",
    "Carrs",
    "Dominick's",
    "SuperValu",
    "Cub Foods",
    "Hornbacher's",
    "Shop 'n Save",
    "Save-A-Lot",
    "Price Rite",
    "Key Food",
    "C-Town",
    "Bravo",
    "Associated Supermarkets",
    "Gristedes",
    "D'Agostino",
    "Fairway Market",
    "Morton Williams",
    "Westside Market",
    "Zabar's",
    "Dean & DeLuca",
    "Eataly",
    "Whole Foods 365",
    "Fresh Market",
    "Earth Fare",
    "Natural Grocers",
    "New Seasons Market",
    "PCC Community Markets",
    "Metropolitan Market",
    "Central Market",
    "Bristol Farms",
    "Gus's Community Market",
    "Mollie Stone's Markets",
    "Andronico's",
    "Lunardi's",
    "Draeger's",
    "Piazza's",
    "Nugget Markets",
    "Oliver's Market",
    "Lazy Acres",
    "Erewhon",
    "Gelson's",
    "Bristol Farms",
    "Jensen's",
    "Jimbo's",
    "Good Earth Natural Foods",
    "Rainbow Grocery",
    "Berkeley Bowl",
    "Woodlands Market",
    "Bi-Rite Market",
    "Mollie Stone's",
    "Andronico's Community Markets",
    "Sigona's Farmers Market",
    "Piedmont Grocery",
    "Monterey Market",
    "Farmer Joe's",
    "Lucky",
    "Save Mart Supermarkets",
    "Smart & Final",
    "Grocery Outlet",
    "Foods Co",
    "FoodMaxx",
    "Maxx Value Foods",
    "El Super",
    "Fiesta Mart",
    "Cardenas Markets",
    "Vallarta Supermarkets",
    "Northgate Market",
    "Superior Grocers",
    "Super King Markets",
    "99 Ranch Market",
    "H Mart",
    "Mitsuwa Marketplace",
    "Uwajimaya",
    "Marukai",
    "Nijiya Market",
    "Tokyo Central",
    "Seiwa Market",
    "Galleria Market",
    "Zion Market",
    "Hong Kong Supermarket",
    "Kam Man Food",
    "Great Wall Supermarket",
    "Pacific Supermarket",
    "SF Supermarket",
    "New May Wah",
    "Fei Long Market",
    "SkyFoods",
    "Good Fortune Supermarket",
    "New York Mart",
    "iFresh",
    "Jusgo Supermarket",
    "U-Mart",
    "T&T Supermarket",
    "FoodyMart",
    "Galleria Supermarket",
    "PAT Supermarket",
    "Oceana Market",
    "Sunny Foodmart",
    "Al Premium Food Mart",
    "FreshCo",
    "No Frills",
    "Food Basics",
    "Real Canadian Superstore",
    "Loblaws",
    "Zehrs",
    "Fortinos",
    "Valu-mart",
    "Your Independent Grocer",
    "Provigo",
    "Maxi",
    "IGA",
    "Sobeys",
    "Safeway Canada",
    "Thrifty Foods",
    "Fresh St. Market",
    "Choices Markets",
    "Urban Fare",
    "Whole Foods Canada",
    "Nature's Emporium",
    "Farm Boy",
    "Longo's",
    "Metro",
    "Foodland",
    "Co-op Atlantic",
    "Save-On-Foods",
    "PriceSmart Foods",
    "Quality Foods",
    "Nesters Market",
    "Buy-Low Foods",
    "Meinhardt Fine Foods",
    "Stong's Market",
    "Famous Foods",
    "Donald's Market",
    "Kinsey's",
    "Meridian Farm Market",
    "Greens Organic and Natural Market",
    "SPUD",
    "Organic Acres",
    "Nature's Fare Markets",
    "Community Natural Foods",
    "Planet Organic",
    "Blush Lane Organic Market",
    "Amaranth Whole Foods",
    "Karma Co-op",
    "The Big Carrot",
    "Fiesta Farms",
    "Fresh City Farms",
    "The Sweet Potato",
    "Green Earth Organics",
    "Pomme Natural Market",
    "Capers Community Markets",
    "SPUD Calgary",
    "Community Farm Store",
    "The Root Cellar",
    "Country Grocer",
    "Peppers Foods",
    "Red Barn Market",
    "Market on Millstream",
    "Market on Yates",
    "The Market Stores",
    "Thrifty Foods",
    "Fairway Markets",
    "Edible Island",
    "Old Farm Market",
    "Nature's Pickin's",
    "The Market on Millstream",
    "Root Cellar Village Green Grocer",
    "Lifestyle Markets",
    "Country Grocer",
    "Tru Value Foods",
    "Askew's Foods",
    "Discovery Organics",
    "Green Organics",
    "Fresh Street Market",
    "Meridian Meats",
    "Jackson's Meats",
    "Windsor Meats",
    "Pete's Meat",
    "Cioffi's Meat Market",
    "Mario's Meat Market",
    "JN&Z Deli",
    "Santa Barbara Market",
    "La Grotta Del Formaggio",
    "Bosa Foods",
    "Cioffi's",
    "Parthenon Supermarket",
    "Mediterranean Specialty Foods",
    "Ayoub's Dried Fruits & Nuts",
    "Sabzi Mandi",
    "Persia Foods",
    "Super Grocer & Pharmacy",
    "Almadina Supermarket",
    "Spice Centre",
    "India Bazaar",
    "Patel Brothers",
    "Subzi Mandi",
    "Apna Bazar",
    "Spice Bazaar",
    "India Cash & Carry",
    "Fruiticana",
    "Chalo FreshCo",
    "Garcha Bros Meat Shop",
    "Famous Foods",
    "India Foods",
    "Surati Sweet Mart",
    "Al Premium",
    "Iqbal Halal Foods",
    "Halal Meat Centre",
    "Madina Fine Foods",
    "Al Kabeer",
    "Al Safa Foods",
    "Al Premium Halal Meat",
    "Sofra Mediterranean Market",
    "Arz Fine Foods",
    "Adonis",
    "Marché Adonis",
    "Marché Istanbul",
    "Marché Anatolia",
    "Tangerine Market",
    "Akin Market",
    "Pars Market",
    "Super Tehran",
    "Super Khorak",
    "Persepolis Market",
    "Shiraz Market",
    "Yekta Market",
    "Super Jahan",
    "Mediterranean Supermarket",
    "Sadaf Foods",
    "Rose Market",
    "Jordan Market",
    "Sultan's Market",
    "Noor Market",
    "Arya Market",
    "Tehran Market",
    "Balady Market",
    "Halalco Supermarket",
    "Zaytouna Market",
    "Al-Aqsa Market",
    "Al-Madina Market",
    "Al-Huda Market",
    "Al-Baraka Market",
    "Al-Falah Market",
    "Al-Rahman Market",
    "Al-Noor Market",
    "Al-Salam Market",
    "Al-Amin Market",
    "Al-Mustafa Market",
    "Al-Khair Market",
    "Al-Madinah Market",
    "Halal Market",
    "Makkah Market",
    "Medina Market",
    "Zamzam Market",
    "Sahara Market",
    "Al-Ameer Market",
    "Al-Amanah Market",
    "Al-Badr Market",
    "Al-Fajr Market",
    "Al-Hidayah Market",
    "Al-Nour Market",
    "Al-Quds Market",
    "Al-Tayyib Market",
    "Al-Wafa Market",
    "Al-Zahra Market",
    "Bismillah Market",
    "Dar Al-Salam Market",
    "Halal Meat Market",
    "Istanbul Market",
    "Jerusalem Market",
    "Mecca Market",
    "Rahma Market",
    "Safa Market",
    "Salam Market",
    "Taj Market",
    "Zabiha Halal Market",
    "Al-Aqsa Halal Meat",
    "Al-Noor Halal Meat",
    "Madina Halal Meat",
    "Safa Halal Meat",
    "Zamzam Halal Meat",
    "Al-Madinah Halal Meat",
    "Al-Huda Halal Meat",
    "Al-Khair Halal Meat",
    "Al-Rahman Halal Meat",
    "Al-Salam Halal Meat",
    "Al-Amin Halal Meat",
    "Al-Mustafa Halal Meat",
    "Al-Falah Halal Meat",
    "Al-Baraka Halal Meat",
    "Halalco Halal Meat",
    "Zaytouna Halal Meat",
    "Makkah Halal Meat",
    "Medina Halal Meat",
    "Sahara Halal Meat",
    "Al-Ameer Halal Meat",
    "Al-Amanah Halal Meat",
    "Al-Badr Halal Meat",
    "Al-Fajr Halal Meat",
    "Al-Hidayah Halal Meat",
    "Al-Nour Halal Meat",
    "Al-Quds Halal Meat",
    "Al-Tayyib Halal Meat",
    "Al-Wafa Halal Meat",
    "Al-Zahra Halal Meat",
    "Bismillah Halal Meat",
    "Dar Al-Salam Halal Meat",
    "Istanbul Halal Meat",
    "Jerusalem Halal Meat",
    "Mecca Halal Meat",
    "Rahma Halal Meat",
    "Safa Halal Meat",
    "Salam Halal Meat",
    "Taj Halal Meat"
    
];